name: $(Build.BuildId)

trigger: none

pool:
  name: Business Central
  demand:
  - Agent.OS -equals WindowsNT
  - docker

resources:
  repositories:
  - repository: softeraDevTasks
    type: github
    name: softera-dev/AzurePipelinesTemplatesForBusinessCentral
    ref: 'refs/heads/master'
    endpoint: github_softera_dev

variables:
- group: BC Common Variables
- name: MainAppFolder
  value: MainApp
- name: TestAppFolder
  value: TestApp
- group: BC16
- name: ImageName
  value: mcr.microsoft.com/businesscentral/onprem:2004
- name: OrganizationName
  value: softera-baltic

extends:
  template: Templates/Pipeline.yml@softeraDevTasks
  parameters:
    appVersionSelection: dockerImageMajorMinorAndManifestBuildRevision